# Generated by Django 4.2.25 on 2025-11-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_person_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='passport_type',
            field=models.CharField(blank=True, choices=[('Книжечка', 'Паспорт-книжечка'), ('ID-картка', 'ID-картка')], max_length=20, verbose_name='Тип паспорта'),
        ),
    ]
